### ISSUE TITLE
Kill label-col?

### ISSUE THREAD

**Issue by mparke** [linode/manager#1020]
Right now we have a div+class that wraps labels, which appears unnecessary for styles applied to primary field labels.

Current:
```
<div className="col-sm-* label-col">
  <label>Name</label>
</div>

// with label col in scss
.label-col {
 // colors, alignment
}
```

Without (wrapping div not needed for labels defined inside a FormGroup):
```
<label className="col-sm-*">Name</label>

// define defaults
label {
 // colors, alignment
}
```

Other labels ( such as defined to the right of checkboxes ) should be the special case.

**Comment by eatonphil** [comment]
My gut preference is to keep the bootstrap columns separate from what would generally be considered the columns' content.

I also don't really think that we should take labels over completely in your proposed way because the label element is super generic and might be appropriate in many places (I think we might already use it in in more ways than we've discussed in meetspace).

However, I am in favor of better naming or organization of what is currently label-col. It is also good to keep in mind the (current or potential) use of `legend` elements in place of labels. So I think we might be well off to use a `Label` class and allow that class to be the default use of labels (and legends) in the app.

This way inputs that don't need special label treatment (color and alignment) can still use the label element easily.

**Comment by mparke** [comment]
Just noting that bootstrap also has a col-form-label which does centering, https://v4-alpha.getbootstrap.com/components/forms/#using-the-grid

**Comment by mparke** [comment]
sounds good @eatonphil
