### ISSUE TITLE
Mockup Nodebalancer add

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1077]

**Comment by eatonphil** [comment]
Two thoughts again (some places are just outlined where the concept exists elsewhere).

First is simpler and not a big change from current NodeBalancer creation:

![screen shot 2017-01-24 at 11 41 28 am](https://cloud.githubusercontent.com/assets/3925912/22257120/0f2856fe-e22b-11e6-8527-93e510d1fc0b.png)
![screen shot 2017-01-24 at 11 41 37 am](https://cloud.githubusercontent.com/assets/3925912/22257121/1211c3be-e22b-11e6-91ef-26254cb5abe8.png)

Second streamlines the config step (so we can potentially move it into an advanced tab or something like the Linodes section):

![screen shot 2017-01-24 at 11 41 48 am](https://cloud.githubusercontent.com/assets/3925912/22257149/2a142db2-e22b-11e6-8e7a-f1e61e8da1bb.png)
![screen shot 2017-01-24 at 11 42 01 am](https://cloud.githubusercontent.com/assets/3925912/22257148/2a10756e-e22b-11e6-8f8a-17b3facd5f76.png)

**Comment by mparke** [comment]
Going to take a stab at an additional version of this, talked to @peaton, re-opening

**Comment by mparke** [comment]
Here's an alternative form, sticks to select/input vs. cards. (Does not take configuration into account, and doesn't have a navigation because i'm still putting sketch things together).

Also, since there's currently only 1 Plan option, I kept it static. This would alternatively be radio selection with only a few options.

![add a nodebalancer](https://cloud.githubusercontent.com/assets/709951/22481987/34849ba2-e7c5-11e6-9c51-832151d489ff.png)

**Comment by mparke** [comment]
per request, card format:

![add a nodebalancer card](https://cloud.githubusercontent.com/assets/709951/22483367/ecacc074-e7ca-11e6-8d48-ee138bb5f8da.png)

**Comment by mparke** [comment]
Closing for now, simple alternative explored.
