### ISSUE TITLE
Add List view header with column labels

### ISSUE THREAD

**Issue by phuegel** [linode/manager#1122]
Add a header title to all List views in new Manager 2.0. eg.) NodeBalancer, DNS Manager, etc. so each column is labeled. This would give users immediate context on the information being displayed without second guessing the data.
![manager nodebalancer 2 0 v1](https://cloud.githubusercontent.com/assets/19841047/22439744/d6436166-e6fe-11e6-8c30-abce0a38d681.png)

#1104
#1102

**Comment by eatonphil** [comment]
We've been back and forth on this a lot actually. We do want to include labels where they might not be obvious, but with a lot of the top-level tables (lists of Linodes, NodeBalancers, DNS zones, etc) we've often felt like having the column name is redundant because it's pretty obvious what a group of numbers that look like an ip address are -- similar for the datacenter / flag, distro, etc.

Deeper into some sections though there are tables where we absolutely do feel the need for labels because the tables are not obvious at all.
