### ISSUE TITLE
Only show unseen notifications by default

### ISSUE THREAD

**Issue by na3d** [linode/manager#1191]

**Comment by mparke** [comment]
do we want some sort of `show more` link with this?

also does it make sense here to provide a way to filter events or have a link to `view all` which presents a page in which you can filter on attributes like `seen`?

@na3d @abemassry @eatonphil let me know if you guys have thoughts. If there's not a clear answer   here, we may want to break this down

**Comment by eatonphil** [comment]
Filter events sounds like a next-level step. I imagined we could get started only initially fetching unseen events. The user would have the option to show all at the bottom that would expand into what the events section currently is. This way we can just move forward incrementally reducing calls (in this case, a smaller initial page load because we only initially fetch unseen events -- even if subsequent polling does need to fetch more pages as it currently does).

**Comment by mparke** [comment]
will start by only fetching unseen

**Comment by na3d** [comment]
For right now unseen with the ability to expand the list sounds good.  Filtering would be great, but more of a bonus.  If we could reduce how often it polls, that would be a very good thing.  We are at 95% of requests being for events right now.

**Comment by na3d** [comment]
Nevermind, I was thinking of a different type of filtering.

**Comment by eatonphil** [comment]
@mparke 

> will start by only fetching unseen

In the first call, yes. But we still do need to fetch the rest afterwards like normal so that (Linode) statuses get updated.
