### ISSUE TITLE
Mockup account settings page

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1195]
see: linode.com/account/settings

**Comment by mparke** [comment]
Keeping it simple, adjusting radio order and updating helper text to match docs.

The general tab structure under account is still WIP. This only focuses on the form.

![account settings](https://cloud.githubusercontent.com/assets/709951/23035001/bea40b5a-f44b-11e6-8b6d-ae6fdacbac2f.png)

**Comment by eatonphil** [comment]
Help text normally goes beneath the input?

**Comment by eatonphil** [comment]
How about making it a checkbox instead?

**Comment by mparke** [comment]
Here's an alternative with checkbox:

![account settings checkbox style](https://cloud.githubusercontent.com/assets/709951/23041883/9a357b6e-f464-11e6-8f10-e7194c8cbc6c.png)

However, I remain in favor of the radio, because it makes explicit the fact that disabling this is considered a legacy option.

**Comment by eatonphil** [comment]
Either way, -1 on the inline text.

**Comment by mparke** [comment]
also in favor of inline in this case, left to right scan, if you have an argument against feel free to comment.

closing for now

**Comment by eatonphil** [comment]
We don't do inline description anywhere else, so I'd rather not start.
