### ISSUE TITLE
Mockup form success state

### ISSUE THREAD

**Issue by mparke** [linode/manager#1268]
form success could be in the structure of simple message at bottom of the form, and/or in a notification if the page is redirected.

**Comment by mparke** [comment]
Various states ( + a couple variations ) shown here.

https://projects.invisionapp.com/boards/8Q36SNPE6ASNW/

**Comment by eatonphil** [comment]
+1 to error/success messages below the button, button text changing and highlighting a newly created element when appropriate. Instead of adding notices in the header, I vote we stick with the progress bar and not automatically redirect on form submit so the user gets a chance to see a response in context.

**Comment by mparke** [comment]
thanks for feedback, sounds good.

**Comment by mparke** [comment]
@na3d @abemassry feel free to comment as well

**Comment by mparke** [comment]
closing for now, can be reopened as needed
