### ISSUE TITLE
Block device assignment should support xen and kvm device names

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#1404]

**Comment by mparke** [comment]
@eatonphil this still outstanding?

**Comment by eatonphil** [comment]
Yep.

**Comment by displague** [comment]
The Rescue and Config disk lists should show xvda instead of sda (etc).
- src/linodes/linode/settings/advanced/components/CreateOrEditConfig.js
- src/linodes/linode/components/RescueMode.js

The api will accept "sda" or "xvda" lettering as appropriate.  It will return "xvda" for disk configs and the config list page currently does not handle that properly.
