### ISSUE TITLE
Mockup StackScripts list

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#181]

**Comment by eatonphil** [comment]
This is probably my single favorite mockup so far. Moving away from icons far and wide as well as just giving control in each row (delete). 

It looks inconsistent with other mockups, but this is the direction I'm heading and the others would follow suit on approval.

![screen shot 2016-07-01 at 2 51 53 pm](https://cloud.githubusercontent.com/assets/3925912/16531649/745ff924-3f9b-11e6-9c6e-b9fee7051e56.png)

**Comment by SirCmpwn** [comment]
I think it's a good start, but I do have some feedback. First, Stackscripts should be its own thing, not live under linodes.

Second, we're going for some kind of a social aspect. This doesn't need to look like the same cookie-cutter UI as everything else, stackscripts should be more of a dedicated hub of scripts that are shared among the community. I'd make each row taller so that each stackscript feels like an independent product rather than a member of a table. I would also draw more attention to the author of the stackscript. Something like cards would be better here than something like lists/tables.

Look at the current stackscripts page: https://www.linode.com/stackscripts This seems like a regression compared to that - it has a dedicated search with distro filtering, a list of popular stackscripts, and the author of each stackscript is shown as part of the title (the titles are bigger, too).

**Comment by SirCmpwn** [comment]
I do like the changes to the tables in general, i.e. leaving icons for text and such

**Comment by eatonphil** [comment]
The current stackscripts this is mocking up is actually [this](https://manager.linode.com/stackscripts).

I think we need to talk more about how to unite the two though.
