### ISSUE TITLE
Implement add a Linode Stackscript selection

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#193]

**Comment by eatonphil** [comment]
Dependent on #213

**Comment by na3d** [comment]
Research needed to best way to find a StackScript for using for create from StackScript.

**Comment by na3d** [comment]
From #2469

Requirement definition (DRAFT):

User story -

As a Linode customer
I want to create a Linode from Stackscripts
So that I can use the known working, updated, popular and curated applications
Linode Manager > Create > From Stackscript selection page/window (default):

List Top 10 with default sort by Number of Active Deployment or Last Revision
“Show more” link at bottom of list
Show both Public and Private Stackscripts in selection window
In the same default window, Linode Customers should be allowed to refine the list using following criteria.

Sort by:

Number of Active Deployments
Last Revision Timestamp
“Featured” listing (Linode staff tagged)
Linode Community Rating (1-5 Linode cubes)
Filter by:

Linux Distribution/Application
Author
Keyword Search

**Comment by rjstires** [comment]
re MAN2-193
