### ISSUE TITLE
Mock-up Stackscripts list

### ISSUE THREAD

**Issue by bralski1** [linode/manager#2128]

**Comment by mparke** [comment]
basic list mocked up: https://projects.invisionapp.com/d/main#/projects/boards/5506566

**Comment by mparke** [comment]
Just closing to move on, but we should re-open when updates needed

**Comment by eatonphil** [comment]
I think having that updated date is nice, but I'd rather us do it in a consistent place on the page across all pages. (Maybe by adding a History tab or adding a History card to the Dashboard tab idk). I can't imagine the rev not being that important to put on list page either...

Stripping it down a tad and adding some of the new things we're throwing it thinking something like this?
<img width="1642" alt="screen shot 2017-06-26 at 9 45 54 pm" src="https://user-images.githubusercontent.com/3925912/27567351-3534991e-5ab9-11e7-98b2-1f5e1714e13d.png">

I think we should also be careful about what we want out of the editing experience... I think the home page of the stackscript should probably be a Dashboard tab like the rest of the pages get with static info on distributions, revisions, deploys, etc. As to the rest of it the best way to make StackScripts editable is unclear given the current API functionality. There is a lot of useful information missing: what were the last edits? (Why would we care about the rev note otherwise?) etc...
