### ISSUE TITLE
docs / webpack throws on node > 8.x

### ISSUE THREAD

**Issue by mparke** [linode/manager#2219]
Have run into this a few times, making a note to address. May be fixed with other changes coming as part of 

https://github.com/linode/manager/issues/2211
and 
https://github.com/linode/manager/issues/2212

**Comment by waynr** [comment]
Is this why the contributing docs recommend node between 6.x and 7.2.1? I'm curious mostly because I wanted to try running tests from the repository but there are no docker images with 7.2.1 and I prefer the later of available options.

I'm also curious because of it's actually 6.x - 7.x then I'll go ahead and submit a PR to update the contributing docs.

**Comment by eatonphil** [comment]
Docs and Manager should be good to go on node 8 as of #2520.
