### ISSUE TITLE
Why is this public?

### ISSUE THREAD

**Issue by joshribakoff** [linode/manager#2288]
Is this repository supposed to be public? I'm a linode customer & saw the link on the new beta. I'm not sure I like the idea of Linode open sourcing it's admin, from a security stand point.

**Comment by eatonphil** [comment]
Hey! Here are two posts we wrote on the subject over a year ago: the [first](https://engineering.linode.com/2016/04/12/Announcing-APIv4.html) when we opened up the new alpha API and the [second](https://engineering.linode.com/2016/05/16/Announcing-the-new-open-source-manager.html) when we open-sourced the Manager itself. To quote from the second article:

> It’s an unusual choice to make a project like this open source. Tom Preston-Werner (cofounder of GitHub) famously said that you should “open source (almost) everything” and argues that you should open source anything that isn’t part of your core business value. Most of our core business value comes from our excellent support team and our high-performance server fleet, as well as some of the software we are keeping proprietary, like our API and everything behind it. You could make the argument (and some of us did during this discussion) that the manager is part of our secret sauce - but it may be a special case. It was decided that the new manager should be a static website that talks to the API, and at that point we’re already delivering all of the code to your browser anyway. We decided to give you the unminified version instead and get some cool open source cred while we’re at it.

Since then we've also moved the [API documentation site itself](https://github.com/linode/manager/tree/master/docs) into this repo so we can share components and styles.

**Comment by joshribakoff** [comment]
Thanks that makes sense.
