### ISSUE TITLE
Can't save deprecated kernels?

### ISSUE THREAD

**Issue by Jonchun** [linode/manager#2325]
It doesn't look like you can save/select deprecated kernels in configuration profiles. 

We should either not display deprecated kernels in the drop-down selection, or display them and allow them to be saved.

**Comment by eatonphil** [comment]
Confirmed. This is an API issue. Will follow up once they've got this fixed.

**Comment by displague** [comment]
This is still the case:
kernels objects currently looks like this,
```
{
architecture: "i386"
id: "linode/4.4.4-x86-linode83" 
kvm: true
label : "4.4.4-x86-linode83"
pvops: true
version: "4.4.4"
xen: true
}
```

**Comment by displague** [comment]
While the kernels end point does not reveal deprecated status, it still returns deprecated kernels and they can be associated to a Linode config in both the API and this cloud manager (this may have been a bug fixed since this issue was reported).

As such, this issue can be closed.  When the API includes deprecated status of kernels (MR-182) we can revisit including that state in the UI somehow.
