### ISSUE TITLE
Mockup create Linode from StackScript

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#2469]

**Comment by phuegel** [comment]
Requirement definition (DRAFT):

User story - 
- As a Linode customer 
- I want to create a Linode from Stackscripts
- So that I can use the known working, updated, popular and curated applications


Linode Manager > Create > From Stackscript selection page/window (default):
- List Top 10 with default sort by Number of Active Deployment or Last Revision
- “Show more” link at bottom of list

In the same default window, Linode Customers should be allowed to refine the list using following criteria.

Sort by: 
- Number of Active Deployments
- Last Revision Timestamp
- “Featured” listing (Linode staff tagged)
- Linode Customer Rating (1-5 Linode cubes)

Filter by:
- Linux Distribution/Application
- Author
- Keyword Search
