### ISSUE TITLE
Columns don't align on list view with backup details

### ISSUE THREAD

**Issue by displague** [linode/manager#264]
The Linode columns don't align on list-view making the data less legible.  I would guess this is due to the length of backup descriptive text.

![image](https://cloud.githubusercontent.com/assets/317653/16819214/6baf9032-4919-11e6-8945-c639ec010e1c.png)

**Comment by eatonphil** [comment]
I don't think we can/should deal with this because these are table rows in completely separate tables. Trying to align table columns in different tables is almost certainly not worth it.

**Comment by na3d** [comment]
I have to agree with Marques, it will look less cluttered if it is consistent.

**Comment by eatonphil** [comment]
I'm not arguing that it wouldn't look nice, I'm suggesting the amount of effort that would need to go into supporting same width columns across tables is not worth it. If we were not using <table> elements, we would lose the ability of the browser to auto resize the column widths to best fit the contents. I don't want to give that up and switch to bootstrap columns so we can have them be the same.

**Comment by SirCmpwn** [comment]
Probably wouldn't be awful, just need to define fixed sizes for each column.

**Comment by displague** [comment]
How about a less verbose `2 hours ago` (rather than `Last backup taken 2 hours ago`)?

**Comment by eatonphil** [comment]
Shortening the text without compromising on understandability would be nice. So `2 hours ago` could maybe do (though there are also indications of first backup to be taken). Here are some other ones too:

* in 2 hours
* 2 hours old
* from 2 hours

Or we could just change the label to read `Last backup` like [here](https://cloud.githubusercontent.com/assets/3925912/16967302/54cb2108-4dd6-11e6-82e7-89b334662137.png) and if no backups are available just say so and link to the backups page instead of indicating when in the future it will happen.

**Comment by SirCmpwn** [comment]
I like "2 hours ago" / "in 2 hours"

**Comment by eatonphil** [comment]
And then on the actual page we could show the full text?

**Comment by SirCmpwn** [comment]
Sure

**Comment by SirCmpwn** [comment]
This only applies to the table view, though. The grid view doesn't have the context of a column heading.

**Comment by eatonphil** [comment]
Hmm... that sucks. I don't want them to have different wording on the list page.

**Comment by SirCmpwn** [comment]
I don't think this is as big of a deal now that we've revised the backup status text to be much shorter.
