### ISSUE TITLE
Reboot with configs only available if the configs page is viewed first

### ISSUE THREAD

**Issue by asauber** [linode/manager#2742]
If reboot is selected in the Linode status dropdown, and there are multiple configs, then a ConfigSelectModalBody should appear after hitting "Confirm" on the first modal which allows the user to choose the config to boot with.

This is only the case if the user first navigates to the <linode> > Settings > Advanced page, probably because this puts the configs into the Redux store.

**Comment by displague** [comment]
Somewhat related, If you attempt to 'power on' when no configs exist, a`config_id: null` will be sent to the boot job, which will fail silently.  A FormGroup error entry could live in the status drop down component to catch config_id or other errors (#2736).

Ideally, it should not be possible to 'Power On' in the absence of configs.  (Rescue mode is the exception to that rule, which is why these complications were discovered while reviewing #2816).
