### ISSUE TITLE
RDNS fails to display update without Refresh

### ISSUE THREAD

**Issue by asauber** [linode/manager#2750]
We got an email about this

"If I click Edit RDNS for linode and enter different address, after save it is not updated on the page. I need to refresh the page to see the value I set."

**Comment by na3d** [comment]
The structure of this data has been flattened since the API call was created, so the new structure is:
ip:{
address:"555.555.555.1"
gateway:"555.555.555.1"
linode_id:555555
prefix:"24"
rdns:"li555-555.members.linode.com"
region:"us-east-1a"
subnet_mask:"255.255.255.0"
type:"public"
}

If you just update that here, it should fix the problem:
https://github.com/linode/manager/blob/develop/src/api/ad-hoc/networking.js#L101-L122

**Comment by displague** [comment]
Consider #1736 and #1353
