### ISSUE TITLE
No payment via PayPal in new Panel

### ISSUE THREAD

**Issue by yyangw** [linode/manager#2961]
there is no payment via paypal in new panel
will Linode cancel the Paypal in the future?

**Comment by displague** [comment]
The manager uses the Public Beta API for everything that it does.  As such, the manager's features follow the progress of the API work.

Since the API recently added PayPal support, https://developers.linode.com/v4/changelogs (2017-12-11), we will be adding a UI for it to the new manager sometime in the next few months.

Our last few iterations have focused on refinement and refactoring.  We'll be revisiting missing components and enhancing the UI in upcoming iterations.

Thanks for using the new interface and providing feedback, yyangw.
