### ISSUE TITLE
Implement Linode detail settings tab

### ISSUE THREAD

**Issue by SirCmpwn** [linode/manager#36]
Just the alerts and the subtabs for now.

**Comment by eatonphil** [comment]
![screen shot 2016-06-01 at 2 40 51 pm](https://cloud.githubusercontent.com/assets/3925912/15721408/de579aaa-2806-11e6-9559-9bfcbc4bad19.png)

![screen shot 2016-06-01 at 2 41 10 pm](https://cloud.githubusercontent.com/assets/3925912/15721419/eae082d2-2806-11e6-8757-d0c8fc922029.png)

**Comment by eatonphil** [comment]
The final two tabs will be converted into a single Advanced tab. Otherwise, the first two pages are ready to go:

![screen shot 2016-06-16 at 5 05 46 pm](https://cloud.githubusercontent.com/assets/3925912/16133229/b47873a0-33e4-11e6-8cea-15435475a8d0.png)
![screen shot 2016-06-16 at 5 06 04 pm](https://cloud.githubusercontent.com/assets/3925912/16133230/b478b946-33e4-11e6-9108-055f1ded5c96.png)

**Comment by eatonphil** [comment]
![screen shot 2016-06-17 at 10 58 38 am](https://cloud.githubusercontent.com/assets/3925912/16164391/dd0ff212-34ab-11e6-981d-27ca8f5a354a.png)

**Comment by SirCmpwn** [comment]
Still needs the actual content of the tabs.

**Comment by eatonphil** [comment]
Oh I see.
