### ISSUE TITLE
backups bleed outside of page-card

### ISSUE THREAD

**Issue by na3d** [linode/manager#425]
When there are too many backups and/or snapshots, the row of backups keeps growing outside of the page's width.  Only 3 backups and 1 snapshot should be active.  We need to decide how we want to handle pending/running snapshots and backups.

![screen shot 2016-09-08 at 10 56 38 am](https://cloud.githubusercontent.com/assets/6047142/18354354/3a82af0a-75b3-11e6-9bb5-4209655347fd.png)

**Comment by eatonphil** [comment]
This is a bug on too many levels, and is getting fixed in @abemassry's #365.

**Comment by eatonphil** [comment]
Actually, this is not relevant to @abemassry's PR and should be considered a separate bug. The real bug is that the following behavior is not respected:

* Only four backup slot cards should **ever** be shown
* Only one snapshot should **ever** be shown
* The first card in the row is for the most recent snapshot
* The last three cards are for the daily, weekly, and fortnightly backups as predicted by #365
