### ISSUE TITLE
Put backups details to bottom of list in detail page

### ISSUE THREAD

**Issue by eatonphil** [linode/manager#443]
In linode details page, put the backups info last. Rename "Backup" label to "Backups".

**Comment by na3d** [comment]
Changing Backup to Backups actually doesn't make sense, because then it will say Backups taken 16 hours ago.

**Comment by eatonphil** [comment]
Maybe just show "Backups" when it is not enabled?

**Comment by na3d** [comment]
I still think in that even for that case Backup is fine, because the plural form holds no additional value (just added, unnecessary, complexity), because what is going on with the backup?  Enable Backups. Oh, I need to enable backups to have a backup.

If this ever displayed more than one backup, I could see it being Backups then.  Otherwise it is a misleading label that changes for some reason.  Potentially making a user think that they only have 1 backup, because it is singular, and only 1 backup displayed, when before, or else where, it is plural.
