### ISSUE TITLE
Regression - Can no longer open any record in new tab

### ISSUE THREAD

**Issue by RoccoHoward** [linode/manager#4903]
In the most recent update to the manager, records can no loner be opened in new tabs.

This was a historical issue that was resolved in https://github.com/linode/manager/pull/870 but seems to have occurred again?

This was working in the previous update (I just migrated 100 domains into the manager) and had the unfortunate and frustrating process of going through each of the domains to fix leaving the double quotes on the TXT records (sigh).

**Comment by martinmckenna** [comment]
Hey @RoccoHoward - thanks for reaching out. This is actually an issue we're actively working to fix. While ctrl+clicking is something that is supported on some entities, such as the primary navigation and the tabs on entity detail screens, it's not something we've implemented everywhere in the app yet.

We have a ticket in our internal project management to track this, and I'll be sure to give you an update as soon as I have one.

**Comment by martinmckenna** [comment]
#4909 fixes the issue with domain table rows not being able to be opened in new tabs.

Opening actual records in new tabs isn't something on the roadmap since domain records do not have dedicated pages in Cloud Manager, but this is feedback we will bring up with stakeholders.

For quick and easy editing of domain records, I'd recommend the [linode-cli](https://github.com/linode/linode-cli) which might save you a lot of time when editing many records
