### ISSUE TITLE
Config/disk padding consistency

### ISSUE THREAD

**Issue by briansteffens** [linode/manager#510]
![screen shot 2016-10-04 at 11 10 19 am](https://cloud.githubusercontent.com/assets/4149249/19079883/234568c6-8a23-11e6-81f6-39d95b7ad14a.png)

**Comment by eatonphil** [comment]
Seems like that .alert div is giving its own margin/padding-bottom when it should not. I'm a little worried about dropping these margin/padding-bottom across the board because I think it would affect some places but I think it might be a good thing. Since this is a small issue, I also recommend the fixer moving the alert to above the disk list to make it more obvious.
