### ISSUE TITLE
Reduce packed js file size

### ISSUE THREAD

**Issue by sskaje** [linode/manager#5236]
I created a support ticket 12264262 about long-time blank page when visit cloud.linode.com when network condition is poor. It's related to two issue, 1 js files are not compressed for transfer, 2 single js file, especially main.xxx.js is too large.

I ran `yarn run build` and checked the output in build/static/js, there are also some files larger than 500kB.

Please:
1 For main.xxx.js, 2.5mB, don't try to pack everything into this file, split into some, at least you can add a loading animation telling users page is loading. Blank page is not acceptable in my company and projects.
2 For those files >= 500kB, please also try to split into multiple files. Last week, I tried to create a new Linode VPS from cloud.linode.com, main section of page is blank for a long time without loading effect, this is also not acceptable.
3 Not sure if support team has reported compression issue to your web server team, in my company it's front-end developers' responsibility telling sysop how to deploy front end files.

**Comment by martinmckenna** [comment]
Hey @sskaje - thanks for the feedback.

This issue is actually something of which we're aware and actively working to fix. I agree with you that we should definitely not be showing blank screens for those with slow or throttled network connections. Currently, we are code-splitting our React components by route, and I think it makes logical sense to implement some loading indicators until we get a more robust solution deployed server-side.

Some other solutions we're currently kicking around include storing non-critical data in session or local storage for faster time to first meaningful paint.

We'll let you know when we have an update on this one.

**Comment by martinmckenna** [comment]
Hi @sskaje - here's an update:

So this morning, we investigated and deployed a fix to gzip all JS and CSS files in the repo. This took our `main.js` file down from ~2.5MB to about ~600KB. This is a huge win and we thank you for pointing this out.

That being said, after that work was deployed, we noticed that the issue still was occurring and after some investigation, it turns out there was a race condition where the app might not load correctly if a network request to `/v4/profile/preferences` finished after a certain block of code was rendered to the DOM. The fix for this is [currently in PR review.](https://github.com/linode/manager/pull/5238). We plan on releasing this hotfix today.

Thanks for the patience and letting us know so we could correctly identify the issue.
