### ISSUE TITLE
Create folders in Object Storage bucket

### ISSUE THREAD

**Issue by andysh-uk** [linode/manager#6351]
The Cloud Manager object storage interface is great, especially with uploading and deleting files.

One thing I'd love to see is the ability to create folders.  I know that there are no folders really, it's just a flat store and it's the object name that creates "virtual" folders, but the Amazon S3 interface allows this by creating a hidden "meta" object for the folder - e.g. /My-New-Folder/.metadata (I don't know the actual filename, it's hidden from both the UI and the API.)

_My use case for this is that I have a private "downloads" bucket where I just keep software installers etc. that I've downloaded. Currently it's easy just to go into the cloud manager and upload the installer straight from my laptop - but only if the folder already exists.  If it doesn't, I then have to open another application (or the CLI on my Linode) to create the folder._

**Comment by johnwcallahan** [comment]
Thanks @andysh-uk; glad you're enjoying the interface.

I agree that the ability to create "folders" in Cloud Manger would be useful, and it's on our roadmap. I spent some time with this, and I believe it can be achieved by creating an empty object with a trailing slash in the name (e.g. "my-folder/"). I've begun discussions with our API team to see if we can support this, since right now the `/object-url` endpoint doesn't honor the trailing slash.

I'll leave this issue open until we have a more solid answer.

**Comment by andysh-uk** [comment]
Thanks @johnwcallahan, useful to know!

I’ve tried playing about with s3cmd but I just can’t fool it into creating an object ending with a trailing slash.

I’ll wait in anticipation to hear the progress from yourselves when you have any!

**Comment by renzyndrome** [comment]
hi, any updates on this? i want to organize my files using the folder creation, thanks

**Comment by chocosobo** [comment]
I also waiting for this
plan to use website image host and need file organization function like folder

**Comment by bnussman-akamai** [comment]
We have added the ability to create object storage folders in Cloud Manager
- https://github.com/linode/manager/pull/8757


https://user-images.githubusercontent.com/115251059/221909317-bceab2ea-dcb6-4777-8ed4-db9001de0adc.mov
