### ISSUE TITLE
Allow changing TTL of NS records

### ISSUE THREAD

**Issue by andysh-uk** [linode/manager#6553]
This is a small, low-priority feature request.

I'd like to be able to change the time-to-live of the default ns[1-5].linode.com NS records.

My reasoning is that the NS records are not likely to change often, so I can afford a high TTL (e.g. 1 day or longer) - however the rest of my domain's records (those I create) could change more frequently, so I leave a lower TTL (1 hour) for these records.

I've set my Default TTL as 1 hour so any record I create uses 1 hour by default.

However, this then makes the default NS records also 1 hour as they are hard-coded to use the default TTL.

The only other way I can achieve this is to set my default TTL as 1 day, but then I have to remember to select a different TTL for every other record I create.  And if I want to migrate my domain's services from one IP to another, with my ideal setup, I just change the default TTL from 1 hour to 5 minutes - but with this workaround, I'd have to change every individual record.

**Comment by andysh-uk** [comment]
Also on the subject of TTLs, I couldn't find anything that says what the "ultimate" default TTL is - i.e. if I set my domain's default TTL to "Default", what value is this?

**Comment by johnwcallahan** [comment]
Hey @andysh-uk, the "ultimate" default TTL is [1 day.](https://www.linode.com/docs/platform/manager/troubleshooting-dns/#set-the-time-to-live-or-ttl)

I've made a note of your feature request to individually change the TTL of the default nameservers, since as you pointed out, currently those can not be edited at all. 

If you need to change the TTL for multiple records at once, automating it with the API is probably your best bet for now. We've discussed introducing the ability to batch actions in Cloud Manager, but haven't gotten to it yet. When we do, this would be a good use case.

Thanks again for the feedback!
