### ISSUE TITLE
A snapshot backup has been created (but not really...)

### ISSUE THREAD

**Issue by ghost** [linode/manager#6804]
Hello everyone,

I've noticed that when I take a backup, I see the percentage progress bar reaching 100%, then I get the notification that "A snapshot backup has been created for ...". The backup section clearly shows the new snapshot and everything appears ok.

But that is not true. Unfortunately, it seems the backup procedure takes a lot longer, a looooooot loooonger. During this unknown loooong time, it is impossible to use the backup image.

I am not sure if this is a bug in linode manager, but the percentage progress bar should actually show the real duration of the backup.

Thank you.

**Comment by johnwcallahan** [comment]
Hey @robo2bobo, the issue is that there's a "needsPostProcessing" status we're not surfacing in the Manager. This can be seen in the API response to `/linode/instances/:linodeId/backups`:

```
...
"status": "needsPostProcessing"
...
```

It's already in our backlog to add this info to the Backups table, and I'll make a note of your request as well. Thanks again.

**Comment by bnussman-akamai** [comment]
The backups table now has more information on the status of a backup
 - https://github.com/linode/manager/pull/8781

![Screenshot 2023-02-28 at 10 55 55 AM](https://user-images.githubusercontent.com/115251059/221907427-a93e1d6d-f80f-43c6-992c-274373578779.jpg)
