### ISSUE TITLE
Some blades are centred on large screens

### ISSUE THREAD

**Issue by andysh-uk** [linode/manager#7648]
This is only a really minor thing, but I find it a little disconcerting that on large screens (I'm on a 1920x1080 monitor) some of the blades open on the right-hand side of the screen, and some in the centre.

For example:

Rename/resize a disk opens on the right:

![image](https://user-images.githubusercontent.com/12907944/117954765-3f21e780-b30f-11eb-9602-580587a87d5b.png)

Other such as Resize/Rebuild a linode opens in the centre:

![image](https://user-images.githubusercontent.com/12907944/117954879-5d87e300-b30f-11eb-8de8-7286e5181d7a.png)

The strange thing is, the animation seems to still start from the right of the screen when it ends up centred, so it's like it should be on the right.

**Comment by bnussman-akamai** [comment]
Hey @andysh-uk

Sorry it's been years since you've gotten a response 😢 

We have a concept of both [Drawers](https://design.linode.com/?path=/docs/components-drawer--documentation) and [Dialogs](https://design.linode.com/?path=/docs/components-dialog--documentation). Drawers open on the right side of your screen. Dialogs open in the center. We think both patterns have value and different use cases so you'll see both throughout Cloud Manager. 

I believe the weird animations you described have been addressed since this issue was opened but let us know if you see otherwise. 

I'm going to close this issue for now, but If you have any specific Dialogs or Drawers that you think we should change, let us know and we're happy to discuss! 🙏
