### ISSUE TITLE
Review bundle and minify optimizations

### ISSUE THREAD

**Issue by briansteffens** [linode/manager#778]
See how small we can get the initial bundle.js file

**Comment by mparke** [comment]
Address after https://github.com/linode/manager/pull/1441

**Comment by eatonphil** [comment]
There's still a while to go. @displague has pointed out that we can specify individual libraries to break out and serve independent of the bundle.js. We do this a little manually (see zxcvbn) but it would be better to do the breaking out in the same place rather than how it works now (`<script>` tag and the library is defined on `window.LibraryName`). We recently switched to webpack2 and there may be some more options for optimization there -- tree-shaking is the big-name one. I'd also look into Google Closure more because most benchmarks I've seen have it as the best optimization. In practice I haven't gotten that to work. Look up open/closed PRs/issues on webpack, optimiz, Google closure, etc.
