### ISSUE TITLE
Linode Private IP column

### ISSUE THREAD

**Issue by tsmgeek** [linode/manager#7895]
Would it be possible to show Private IP (if enabled) in the Linode list, or make it an optional column, ie have a selection of what columns you wish to see.

**Comment by kutlay** [comment]
+1 to this

**Comment by bnussman-akamai** [comment]
Hey @tsmgeek  👋 

Sorry it's been so long since you've gotten a response. This is something we **absolutely** want to implement in Cloud Manager. I've created an internal ticket (`M3-8882`) to start an effort of improving Cloud Manager's tables. We don't have a timeline for this, but hope to work on it as soon as possible!

Our goal will be to build features like 
- Ability to filter columns
- Ability to search by a term on each column
- Ability to re-order column
- Ability to customize which columns are shown
- Ability to perform batch actions on rows
- Ability to perform complex search queries

I'm going to close this issue because we are tracking it internally but feel free to reach out if you have any other ideas, comments, or concerns
