### ISSUE TITLE
Fix notification collapse on click

### ISSUE THREAD

**Issue by mparke** [linode/manager#857]
Clicking an item (2 times in total) in the notifications panel changes the page underneath, but does not close the panel.

![screen shot 2016-12-22 at 1 57 47 pm](https://cloud.githubusercontent.com/assets/709951/21436894/bec5c606-c84e-11e6-9c9e-0ac1f6522fba.png)

**Comment by eatonphil** [comment]
For what it's worth this was intentional. This is also just a random experiment at this point so intended behavior is completely up for discussion. (Including whether clicking on a thing links you to a page at all or if clicking on the first time does it -- as opposed to the current second click doing it for an unread notification.)

**Comment by briansteffens** [comment]
Personally I don't like sequential clicks having different effects. Reasonable solutions IMO:

Maybe clicking the event always marks it read but doesn't redirect. Then we could have a 'View' link (or whatever) which does redirect and closes the notifications pane.

**Comment by eatonphil** [comment]
@briansteffens +1 I've been leaning toward that as well.
