### ISSUE TITLE
Show private IP in Nodebalancers details

### ISSUE THREAD

**Issue by thinhbuzz** [linode/manager#8816]
When I use the firewall, I need the private IP of the Nodebalancers but can't find this information in the details page. I am required to create a linode server so that I can get the private IP and use it to configure the firewall.
![image](https://user-images.githubusercontent.com/8065692/220898758-95db1a5e-0bdf-4533-a66e-c27a58ed2b61.png)

**Comment by bnussman-akamai** [comment]
Hey @thinhbuzz, currently there is no way to get the exact private IP of a Nodebalancer because Nodebalancers are highly available and may use multiple private IP addresses to reach your Linodes. You should be able to allow connections from the following range `192.168.255.0/24` in your firewall to get this to work. 

Source: https://github.com/linode/docs/pull/5786/files#diff-9ffba81f79e5dec52c5fcc137807be89aa2dc27315a7cacc347317cf951a82c3R76

**Comment by thinhbuzz** [comment]
@bnussman-akamai thanks for your info
